/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as LobbyImport } from './routes/lobby'
import { Route as GameImport } from './routes/game'
import { Route as DeploymentImport } from './routes/deployment'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SignupRoute = SignupImport.update({
          id: '/signup',path: '/signup',getParentRoute: () => rootRoute
        }as any)

const LoginRoute = LoginImport.update({
          id: '/login',path: '/login',getParentRoute: () => rootRoute
        }as any)

const LobbyRoute = LobbyImport.update({
          id: '/lobby',path: '/lobby',getParentRoute: () => rootRoute
        }as any)

const GameRoute = GameImport.update({
          id: '/game',path: '/game',getParentRoute: () => rootRoute
        }as any)

const DeploymentRoute = DeploymentImport.update({
          id: '/deployment',path: '/deployment',getParentRoute: () => rootRoute
        }as any)

const IndexRoute = IndexImport.update({
          id: '/',path: '/',getParentRoute: () => rootRoute
        }as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
          id: '/'
          path: '/'
          fullPath: '/'
          preLoaderRoute: typeof IndexImport
          parentRoute: typeof rootRoute
        }
'/deployment': {
          id: '/deployment'
          path: '/deployment'
          fullPath: '/deployment'
          preLoaderRoute: typeof DeploymentImport
          parentRoute: typeof rootRoute
        }
'/game': {
          id: '/game'
          path: '/game'
          fullPath: '/game'
          preLoaderRoute: typeof GameImport
          parentRoute: typeof rootRoute
        }
'/lobby': {
          id: '/lobby'
          path: '/lobby'
          fullPath: '/lobby'
          preLoaderRoute: typeof LobbyImport
          parentRoute: typeof rootRoute
        }
'/login': {
          id: '/login'
          path: '/login'
          fullPath: '/login'
          preLoaderRoute: typeof LoginImport
          parentRoute: typeof rootRoute
        }
'/signup': {
          id: '/signup'
          path: '/signup'
          fullPath: '/signup'
          preLoaderRoute: typeof SignupImport
          parentRoute: typeof rootRoute
        }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute,'/deployment': typeof DeploymentRoute,'/game': typeof GameRoute,'/lobby': typeof LobbyRoute,'/login': typeof LoginRoute,'/signup': typeof SignupRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute,'/deployment': typeof DeploymentRoute,'/game': typeof GameRoute,'/lobby': typeof LobbyRoute,'/login': typeof LoginRoute,'/signup': typeof SignupRoute
}

export interface FileRoutesById {
  '__root__': typeof rootRoute,
  '/': typeof IndexRoute,'/deployment': typeof DeploymentRoute,'/game': typeof GameRoute,'/lobby': typeof LobbyRoute,'/login': typeof LoginRoute,'/signup': typeof SignupRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'|'/deployment'|'/game'|'/lobby'|'/login'|'/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/'|'/deployment'|'/game'|'/lobby'|'/login'|'/signup'
  id: '__root__'|'/'|'/deployment'|'/game'|'/lobby'|'/login'|'/signup'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute,DeploymentRoute: typeof DeploymentRoute,GameRoute: typeof GameRoute,LobbyRoute: typeof LobbyRoute,LoginRoute: typeof LoginRoute,SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,DeploymentRoute: DeploymentRoute,GameRoute: GameRoute,LobbyRoute: LobbyRoute,LoginRoute: LoginRoute,SignupRoute: SignupRoute
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()


/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/deployment",
        "/game",
        "/lobby",
        "/login",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/deployment": {
      "filePath": "deployment.tsx"
    },
    "/game": {
      "filePath": "game.tsx"
    },
    "/lobby": {
      "filePath": "lobby.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    }
  }
}
ROUTE_MANIFEST_END */